export const GET_FAVORITE_SEEK_PENDING = 'GET_FAVORITE_SEEK_PENDING'
export const GET_FAVORITE_SEEK_SUCCESS = 'GET_FAVORITE_SEEK_SUCCESS'
export const GET_FAVORITE_SEEK_ERROR = 'GET_FAVORITE_SEEK_ERROR'

export const GET_FAVORITE_BUTTON_STATE_PENDING = 'GET_FAVORITE_BUTTON_STATE_PENDING'
export const GET_FAVORITE_BUTTON_STATE_SUCCESS = 'GET_FAVORITE_BUTTON_STATE_SUCCESS'
export const GET_FAVORITE_BUTTON_STATE_ERROR = 'GET_FAVORITE_BUTTON_STATE_ERROR'
export const GET_WATCH_BUTTON_STATE_PENDING = 'GET_WATCH_BUTTON_STATE_PENDING'
export const GET_WATCH_BUTTON_STATE_SUCCESS = 'GET_WATCH_BUTTON_STATE_SUCCESS'
export const GET_WATCH_BUTTON_STATE_ERROR = 'GET_WATCH_BUTTON_STATE_ERROR'

export const getFavPending = () => ({
  type: GET_FAVORITE_SEEK_PENDING
})

export const getFavSuccess = (payload = []) => ({
  type: GET_FAVORITE_SEEK_SUCCESS,
  payload: payload
})

export const getFavError = () => ({
  type: GET_FAVORITE_SEEK_ERROR
})